package com.myspace2.myjava;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class mybusines implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigInteger javaMe;

	public mybusines() {
	}

	public java.math.BigInteger getJavaMe() {
		return this.javaMe;
	}

	public void setJavaMe(java.math.BigInteger javaMe) {
		this.javaMe = javaMe;
	}

	public mybusines(java.math.BigInteger javaMe) {
		this.javaMe = javaMe;
	}

}